src/Entity/Agence.php
<?php

namespace App\Entity;

use App\Repository\AgenceRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: AgenceRepository::class)]
class Agence
{
    #[ORM\ManyToOne(inversedBy: 'agencesClass' )]
     private ?Activite $activites = null ;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(message:"Le nom de l'agence est obligatoire")]
    #[Assert\Regex(pattern: '/^[a-z\s]+$/i',htmlPattern: '^[a-zA-Z\s]+$',message:"Le nom de l'agence doit contenir que des lettres")]
    private ?string $Nom = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"le nombre de participant doit est obligatoire ")]
    private ?int $nbr_participant = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"le Devis est obligatoire ")]
    #[Assert\Positive(message:"Le devis doit être positif ")]
    private ?int $Devis = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"le numéro de téléphone est obligatoire ")]
    #[Assert\Length(
        min: 8,
        max: 8,
        minMessage: "Numero de téléphone invalide",
        maxMessage: "Numero de téléphone invalide"
    )]
    private ?int $Num_tel = null;

    #[ORM\ManyToOne(inversedBy: 'Agences')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Activite $activite = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getNbrParticipant(): ?int
    {
        return $this->nbr_participant;
    }

    public function setNbrParticipant(int $nbr_participant): self
    {
        $this->nbr_participant = $nbr_participant;

        return $this;
    }

    public function getDevis(): ?int
    {
        return $this->Devis;
    }

    public function setDevis(int $Devis): self
    {
        $this->Devis = $Devis;

        return $this;
    }

    public function getNumTel(): ?int
    {
        return $this->Num_tel;
    }

    public function setNumTel(int $Num_tel): self
    {
        $this->Num_tel = $Num_tel;

        return $this;
    }

    public function getActivite(): ?Activite
    {
        return $this->activite;
    }

    public function setActivite(?Activite $activite): self
    {
        $this->activite = $activite;

        return $this;
    }
}

src/Form/AgenceType.php
<?php

namespace App\Form;

use App\Entity\Agence;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AgenceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('nbr_participant')
            ->add('Devis')
            ->add('Num_tel')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Agence::class,
        ]);
    }
}

src/Controller/AgenceController.php
<?php

namespace App\Controller;

use App\Entity\Agence;
use App\Form\AgenceType;
use App\Repository\AgenceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/agence')]
class AgenceController extends AbstractController
{
    #[Route('/', name: 'app_agence_index', methods: ['GET'])]
    public function index(AgenceRepository $agenceRepository): Response
    {
        return $this->render('agence/index.html.twig', [
            'agences' => $agenceRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_agence_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AgenceRepository $agenceRepository): Response
    {
        $agence = new Agence();
        $form = $this->createForm(AgenceType::class, $agence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $agenceRepository->save($agence, true);

            return $this->redirectToRoute('app_agence_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('agence/new.html.twig', [
            'agence' => $agence,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_agence_show', methods: ['GET'])]
    public function show(Agence $agence): Response
    {
        return $this->render('agence/show.html.twig', [
            'agence' => $agence,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_agence_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Agence $agence, AgenceRepository $agenceRepository): Response
    {
        $form = $this->createForm(AgenceType::class, $agence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $agenceRepository->save($agence, true);

            return $this->redirectToRoute('app_agence_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('agence/edit.html.twig', [
            'agence' => $agence,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_agence_delete', methods: ['POST'])]
    public function delete(Request $request, Agence $agence, AgenceRepository $agenceRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$agence->getId(), $request->request->get('_token'))) {
            $agenceRepository->remove($agence, true);
        }

        return $this->redirectToRoute('app_agence_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/Agence/_delete_form.html.twig
<form method="post" action="{{ path('app_agence_delete', {'id': agence.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ agence.id) }}">
    <button class="btn">Delete</button>
</form>

templates/Agence/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/Agence/edit.html.twig
<!DOCTYPE html>
<html lang="en">
<body class="g-sidenav-show  bg-gray-200">
  
  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">

      <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Modifier l'agence</h6>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">

        <tbody>
    
    
    
    
    
    {{ include('agence/_form.html.twig', {'button_label': 'Update'}) }}

    
     </tbody>
    </table>
     </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</body>
    
    
    
    
    
    <a href="{{ path('app_agence_index') }}"><span class="badge badge-sm bg-gradient-success">Back to list</span></a>
<br></br>
    {{ include('agence/_delete_form.html.twig') }}
{% endblock %}

templates/Agence/index.html.twig
{% extends 'base-back.html.twig' %}

{% block content %}
 


<!DOCTYPE html>
<html lang="en">
<body class="g-sidenav-show  bg-gray-200">
  
  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
     
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">List des Agences </h6>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">





        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Nbr_participant</th>
                <th>Devis</th>
                <th>Num_tel</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for agence in agences %}
            <tr>
                <td> <div class="d-flex px-2 py-1"> {{ agence.id }}</td>
                <td> <div class="d-flex px-2 py-1"> {{ agence.Nom }}</td>
                <td> <div class="d-flex px-2 py-1"> {{ agence.nbrParticipant }}</td>
                <td> <div class="d-flex px-2 py-1"> {{ agence.Devis }}</td>
                <td> <div class="d-flex px-2 py-1"> {{ agence.NumTel }}</td>
                <td>
                
                    <a  href="{{ path('app_agence_show', {'id': agence.id}) }}"> <span class="badge badge-sm bg-gradient-success">Show</span></a>
                    <a href="{{ path('app_agence_edit', {'id': agence.id}) }}"><span class="badge badge-sm bg-gradient-success">Edit</span></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
        <div class="d-flex px-2 py-1">
    <a href="{{ path('app_agence_new') }}"><span class="badge badge-sm bg-gradient-success">Create new</span></a>

    </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</body>

</html>
{% endblock %}

templates/Agence/new.html.twig
{% extends 'base-back.html.twig' %}
{% block content %}


<!DOCTYPE html>
<html lang="en">
<body class="g-sidenav-show  bg-gray-200">
  
  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
     
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Creer une nouvelle agence</h6>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">


        <tbody>

        
       {{ include('agence/_form.html.twig') }}

        </tbody>
    </table>
        <div class="d-flex px-2 py-1">
   <a href="{{ path('app_agence_index') }}"><span class="badge badge-sm bg-gradient-success">Back to list </span></a>

    </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</body>

</html>
{% endblock %}

templates/Agence/show.html.twig
{% extends 'base-back.html.twig' %}
{% block content %}


<!DOCTYPE html>
<html lang="en">
<body class="g-sidenav-show  bg-gray-200">
  
  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">

      <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Agence</h6>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">

        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ agence.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ agence.Nom}}</td>
            </tr>
            <tr>
                <th>Nbr_participant</th>
                <td>{{ agence.nbrParticipant }}</td>
            </tr>
            <tr>
                <th>Devis</th>
                <td>{{ agence.Devis }}</td>
            </tr>
            <tr>
                <th>Num_tel</th>
                <td>{{ agence.NumTel }}</td>
            </tr>
            
        </tbody>
    </table>
     </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</body>

    <a href="{{ path('app_agence_index') }}"><span class="badge badge-sm bg-gradient-success">Back to list</span></a>

    <a href="{{ path('app_agence_edit', {'id': agence.id}) }}"><span class="badge badge-sm bg-gradient-success">Edite</span></a>
<br></br>
    {{ include('agence/_delete_form.html.twig') }}
{% endblock %}